######## Kubernetes and Helm image##############
FROM ubuntu
RUN apt-get update
RUN apt install curl -y
RUN apt install wget -y
RUN apt install vim -y
RUN apt install git -y
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin
RUN apt-get update && apt-get -y install apt-transport-https
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh
